// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Proiect_ASPDOTNET.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Proiect_ASPDOTNET.Models.Entities.Companie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<string>("Adresa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CUI")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompanieId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("DataInregistrare")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nume")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Telefon")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CompanieId")
                        .IsUnique();

                    b.ToTable("Companii");
                });

            modelBuilder.Entity("Proiect_ASPDOTNET.Models.Entities.Depozit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<string>("Adresa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CapacitateMaxima")
                        .HasColumnType("int");

                    b.Property<int>("CompanieId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataDeschidere")
                        .HasColumnType("datetime2");

                    b.Property<string>("DepozitId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("Latitudine")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Longitudine")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Nume")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("CompanieId");

                    b.HasIndex("DepozitId")
                        .IsUnique();

                    b.ToTable("Depozite");
                });

            modelBuilder.Entity("Proiect_ASPDOTNET.Models.Entities.LogActivitate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Actiune")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AdresaIP")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DataOra")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DepozitId")
                        .HasColumnType("int");

                    b.Property<string>("Detalii")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DepozitId");

                    b.HasIndex("UserId");

                    b.ToTable("LogActivitati");
                });

            modelBuilder.Entity("Proiect_ASPDOTNET.Models.Entities.Marfa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CapacitateCurenta")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataAdaugare")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataUltimaModificare")
                        .HasColumnType("datetime2");

                    b.Property<int>("DepozitId")
                        .HasColumnType("int");

                    b.Property<string>("Descriere")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Etaj")
                        .HasColumnType("int");

                    b.Property<string>("MarfaId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Pozitie")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("PretUnitar")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Raft")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SKU")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UnitateMasura")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Zona")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DepozitId");

                    b.ToTable("Marfuri");
                });

            modelBuilder.Entity("Proiect_ASPDOTNET.Models.Entities.Sarcina", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DataFinalizare")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataLimita")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descriere")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Finalizata")
                        .HasColumnType("bit");

                    b.Property<int>("Prioritate")
                        .HasColumnType("int");

                    b.Property<int>("PuncteReward")
                        .HasColumnType("int");

                    b.Property<string>("Titlu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Sarcini");
                });

            modelBuilder.Entity("Proiect_ASPDOTNET.Models.Entities.Tranzactii", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Cantitate")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataTranzactie")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DepozitDestinatieId")
                        .HasColumnType("int");

                    b.Property<int?>("DepozitSursaId")
                        .HasColumnType("int");

                    b.Property<int>("MarfaId")
                        .HasColumnType("int");

                    b.Property<string>("Observatii")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Tip")
                        .HasColumnType("int");

                    b.Property<string>("TranzactieId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<decimal>("ValoareTotala")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("DepozitDestinatieId");

                    b.HasIndex("DepozitSursaId");

                    b.HasIndex("MarfaId");

                    b.HasIndex("UserId");

                    b.ToTable("Tranzactii");
                });

            modelBuilder.Entity("Proiect_ASPDOTNET.Models.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activ")
                        .HasColumnType("bit");

                    b.Property<int?>("CompanieId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataCreare")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DepozitId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("NumeComplet")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PuncteReward")
                        .HasColumnType("int");

                    b.Property<int>("Rol")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("CompanieId");

                    b.HasIndex("DepozitId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Proiect_ASPDOTNET.Models.Entities.Depozit", b =>
                {
                    b.HasOne("Proiect_ASPDOTNET.Models.Entities.Companie", "Companie")
                        .WithMany("Depozite")
                        .HasForeignKey("CompanieId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Companie");
                });

            modelBuilder.Entity("Proiect_ASPDOTNET.Models.Entities.LogActivitate", b =>
                {
                    b.HasOne("Proiect_ASPDOTNET.Models.Entities.Depozit", "Depozit")
                        .WithMany()
                        .HasForeignKey("DepozitId");

                    b.HasOne("Proiect_ASPDOTNET.Models.Entities.User", "User")
                        .WithMany("LogActivitati")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Depozit");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Proiect_ASPDOTNET.Models.Entities.Marfa", b =>
                {
                    b.HasOne("Proiect_ASPDOTNET.Models.Entities.Depozit", "Depozit")
                        .WithMany("Marfuri")
                        .HasForeignKey("DepozitId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Depozit");
                });

            modelBuilder.Entity("Proiect_ASPDOTNET.Models.Entities.Sarcina", b =>
                {
                    b.HasOne("Proiect_ASPDOTNET.Models.Entities.User", "User")
                        .WithMany("Sarcini")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Proiect_ASPDOTNET.Models.Entities.Tranzactii", b =>
                {
                    b.HasOne("Proiect_ASPDOTNET.Models.Entities.Depozit", "DepozitDestinatie")
                        .WithMany("TranzactiiDestinatie")
                        .HasForeignKey("DepozitDestinatieId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Proiect_ASPDOTNET.Models.Entities.Depozit", "DepozitSursa")
                        .WithMany("TranzactiiSursa")
                        .HasForeignKey("DepozitSursaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Proiect_ASPDOTNET.Models.Entities.Marfa", "Marfa")
                        .WithMany("Tranzactii")
                        .HasForeignKey("MarfaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Proiect_ASPDOTNET.Models.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DepozitDestinatie");

                    b.Navigation("DepozitSursa");

                    b.Navigation("Marfa");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Proiect_ASPDOTNET.Models.Entities.User", b =>
                {
                    b.HasOne("Proiect_ASPDOTNET.Models.Entities.Companie", "Companie")
                        .WithMany("Utilizatori")
                        .HasForeignKey("CompanieId");

                    b.HasOne("Proiect_ASPDOTNET.Models.Entities.Depozit", "Depozit")
                        .WithMany("Utilizatori")
                        .HasForeignKey("DepozitId");

                    b.Navigation("Companie");

                    b.Navigation("Depozit");
                });

            modelBuilder.Entity("Proiect_ASPDOTNET.Models.Entities.Companie", b =>
                {
                    b.Navigation("Depozite");

                    b.Navigation("Utilizatori");
                });

            modelBuilder.Entity("Proiect_ASPDOTNET.Models.Entities.Depozit", b =>
                {
                    b.Navigation("Marfuri");

                    b.Navigation("TranzactiiDestinatie");

                    b.Navigation("TranzactiiSursa");

                    b.Navigation("Utilizatori");
                });

            modelBuilder.Entity("Proiect_ASPDOTNET.Models.Entities.Marfa", b =>
                {
                    b.Navigation("Tranzactii");
                });

            modelBuilder.Entity("Proiect_ASPDOTNET.Models.Entities.User", b =>
                {
                    b.Navigation("LogActivitati");

                    b.Navigation("Sarcini");
                });
#pragma warning restore 612, 618
        }
    }
}
